FROM oven/bun:1.3.4-slim
WORKDIR /app

COPY package.json bun.lock* ./
COPY apps/api/package.json ./apps/api/
RUN bun install

COPY packages ./packages
COPY apps/api ./apps/api
COPY turbo.json ./

EXPOSE 3001

ENV NODE_ENV=development
ENV PORT=3001

CMD ["bun", "run", "--watch", "apps/api/index.ts"]

